icons_format = "{icon}"
scrolling = "natural"

[theme]
theme = "gruvbox-dark"

[theme.overrides]
separator = ""

[icons]
icons = "awesome5"

[[block]]
block = "music"
player = "spotify"
format = " $icon {$combo.str(max_w:20) $play $next |}"

[[block]]
block = "sound"
max_vol = 150

[[block]]
block = "net"
device = "wlp3s0"

[[block]]
block = "temperature"
interval = 5
format = " $icon $average "
chip = "*-isa-*"
inputs = ["TCXC"]

[[block]]
block = "memory"
format = " $icon $mem_avail "

[[block]]
block = "disk_space"

[[block]]
block = "cpu"
interval = 5

[[block]]
block = "backlight"
device = "acpi_video0"

[[block]]
block = "battery"
interval = 5

[[block]]
block = "time"
interval = 60
format = " $icon $timestamp.datetime(f:'%m/%d %R') "
